---
title: "Global OA Report"
format: html
echo: False
---

```{python}
import parameters
from process import *

data = report_numbers(af=None, quarto=True)
git = git_status(af=None, quarto=True)
```

# THE GLOBAL STATE OF OPEN ACCESS `{python} parameters.REPORT_YEAR`

## Summary

At the end of `{python} data['report_year']` the global open access level for research published in
`{python} data['census_year']['year']` reached `{python} data['census_year']['pc_open']`% with an increase of
`{python} data['census_year']['pc_open_increase']`% compared to
outputs published in `{python} data['comparison_year']['year']`. Access provided through publisher websites
increased by `{python} data['census_year']['pc_publisher_increase']`% to
`{python} data['census_year']['pc_publisher']`% for `{python} data['comparison_year']['year']` publications.

```{python}
fig_oa_global_trend(af=None, quarto=True)
```

Access through other platforms was `{python} data['census_year']['pc_other_platform']`% in
`{python} data['census_year']['year']` with no growth compared to `{python} data['comparison_year']['year']` publications. 
This may be the result of embargos depressing rates of access through repositories for the most recent years of 
publication. Zero-embargo access through non-publisher platforms for `{python} data['census_year']['year']` 
was `{python} data['census_year']['pc_other_platform_zero_embargo']`% of all outputs available through other platforms.
Future reports will track the evolution of immediate other platform open access over time.

## Open Access by Country

The countries with the highest levels of open access continue to be countries will small publication output numbers, 
with Indonesia and Brazil dominating amongst countries with more than 10,000 outputs in 
`{python} data['census_year']['year']` with a set of European countries following. 
European countries tend to show higher levels of open access through other platforms, compared to other countries
with high levels of accessibility and this is in part due to generally shorter embargos, particularly in north-western
Europe.

```{python}
fig_oa_country_compare(af=None, quarto=True)
```

## Methodology

The primary data table used was the final DOI table in the Academic Observatory for 
`{python} data['report_year']`, bigquery://academic-observatory.observatory.doi20211211. Open Access types and
the analysis for categorising them from Unpaywall are as described on the 
[COKI Open Access Dashboard](https://open.coki.ac/how/).

This report was generated automatically from the source data on ##### and the relevant code and
state of the repository is available [on github](`{python} git['remote_url']`):

* Commit hash: `{python} git['sha']`
* Branch: `{python} git['branch']`